
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.health.ping.enabled: false
management.health.circuitbreakers.enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidengWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 20
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 40
        eventConsumerBufferSize: 10
    instances:
      DemoCircuitBreaker:
        baseConfig: default

# To see the circuit breaker log, enable the debug level for below package
logging.level:
  io.github.resilience4j.circuitbreaker: debug